/**
 * Pure generators for Copilot custom agents, a lean tool set, and a plan prompt.
 *
 *  - `.github/agents/plan.agent.md`      reasoning model, read-only tools
 *  - `.github/agents/implement.agent.md` cheaper model, edit/run tools
 *  - `.github/tokenmin.toolsets.jsonc`   shareable lean tool sets
 *  - `.github/prompts/plan.prompt.md`    a reusable planning prompt
 *
 * Restricting each agent to the tools it needs directly cuts tool-definition
 * and tool-output tokens. No `vscode` import — fully unit-testable.
 */
import { GeneratedFile } from '../apply/types';
import { GeneratorContext, testCommandFor } from './types';

export const PLAN_AGENT_PATH = '.github/agents/plan.agent.md';
export const IMPLEMENT_AGENT_PATH = '.github/agents/implement.agent.md';
export const TOOLSET_PATH = '.github/tokenmin.toolsets.jsonc';
export const PLAN_PROMPT_PATH = '.github/prompts/plan.prompt.md';

/** Read-only tools sufficient to explore and produce a plan. */
export const PLAN_TOOLS = ['codebase', 'search', 'usages', 'fetch', 'githubRepo', 'findTestFiles', 'problems', 'changes'];

/** Tools needed to implement an approved plan and verify it. */
export const IMPLEMENT_TOOLS = ['codebase', 'search', 'usages', 'editFiles', 'runCommands', 'runTasks', 'findTestFiles', 'problems', 'changes'];

export interface AgentGenOptions {
  /** Model for the Plan agent (a reasoning model). */
  planModel?: string;
  /** Model for the Implement agent (a cheaper model). */
  implementModel?: string;
}

export const DEFAULT_PLAN_MODEL = 'Claude Sonnet 4';
export const DEFAULT_IMPLEMENT_MODEL = 'GPT-4.1';

export function buildAgentArtifacts(ctx: GeneratorContext, options: AgentGenOptions = {}): GeneratedFile[] {
  return [
    buildPlanAgent(ctx, options),
    buildImplementAgent(ctx, options),
    buildToolSet(),
    buildPlanPrompt(ctx),
  ];
}

export function buildPlanAgent(ctx: GeneratorContext, options: AgentGenOptions = {}): GeneratedFile {
  const model = options.planModel ?? DEFAULT_PLAN_MODEL;
  const frontmatter = renderFrontmatter({
    description: 'Plan a change: explore the codebase (read-only) and produce a concrete, step-by-step plan.',
    tools: PLAN_TOOLS,
    model,
  });
  const body = [
    'You are the **Plan** agent. Your job is to produce a precise implementation plan — you do',
    'not edit files or run commands.',
    '',
    '- Explore only what is needed; prefer reading the specific files involved over broad searches.',
    ctx.hasArchitectureDoc ? '- Start from `ARCHITECTURE.md` to locate the relevant area.' : '- Identify the relevant area before searching widely.',
    '- Output: the files to change, the change in each, risks, and how to verify.',
    '- Keep the plan short and concrete. Hand off to the **Implement** agent.',
    '',
  ].join('\n');
  return { relativePath: PLAN_AGENT_PATH, content: frontmatter + body };
}

export function buildImplementAgent(ctx: GeneratorContext, options: AgentGenOptions = {}): GeneratedFile {
  const model = options.implementModel ?? DEFAULT_IMPLEMENT_MODEL;
  const testCmd = testCommandFor(ctx.stack);
  const frontmatter = renderFrontmatter({
    description: 'Implement an approved plan with minimal, scoped edits and verify it.',
    tools: IMPLEMENT_TOOLS,
    model,
  });
  const body = [
    'You are the **Implement** agent. You execute an already-approved plan.',
    '',
    '- Make the minimal edits the plan calls for; do not refactor beyond scope.',
    '- Do not touch generated/dependency directories.',
    testCmd ? `- Verify with \`${testCmd}\` and fix failures you introduce.` : '- Verify your change with the project test command.',
    '- If the plan is wrong or incomplete, stop and report rather than improvising broadly.',
    '',
  ].join('\n');
  return { relativePath: IMPLEMENT_AGENT_PATH, content: frontmatter + body };
}

export function buildToolSet(): GeneratedFile {
  const content =
    [
      '// Lean tool sets generated by Token Optimizer.',
      '// Fewer tools => fewer tool definitions and smaller tool outputs per request.',
      '{',
      '  "plan-readonly": {',
      `    "tools": ${JSON.stringify(PLAN_TOOLS)},`,
      '    "description": "Read-only tools for planning",',
      '    "icon": "search"',
      '  },',
      '  "implement-lean": {',
      `    "tools": ${JSON.stringify(IMPLEMENT_TOOLS)},`,
      '    "description": "Lean tools for implementing an approved plan",',
      '    "icon": "tools"',
      '  }',
      '}',
      '',
    ].join('\n');
  return { relativePath: TOOLSET_PATH, content };
}

export function buildPlanPrompt(ctx: GeneratorContext): GeneratedFile {
  const frontmatter = renderFrontmatter({
    description: `Produce an implementation plan for a task in ${ctx.repoName}.`,
    mode: 'plan',
  });
  const body = [
    'Plan the following task. Do not edit files — produce a step-by-step plan only.',
    '',
    'Task: ${input:task}',
    '',
    'Return: files to change, the change in each, risks, and how to verify.',
    '',
  ].join('\n');
  return { relativePath: PLAN_PROMPT_PATH, content: frontmatter + body };
}

// ── frontmatter rendering ───────────────────────────────────────────────────

interface FrontmatterFields {
  description: string;
  tools?: string[];
  model?: string;
  mode?: string;
}

function renderFrontmatter(fields: FrontmatterFields): string {
  const lines: string[] = ['---'];
  lines.push(`description: '${escapeSingleQuotes(fields.description)}'`);
  if (fields.mode) {
    lines.push(`mode: ${fields.mode}`);
  }
  if (fields.tools) {
    lines.push(`tools: [${fields.tools.map((t) => `'${t}'`).join(', ')}]`);
  }
  if (fields.model) {
    lines.push(`model: ${fields.model}`);
  }
  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

function escapeSingleQuotes(text: string): string {
  return text.replace(/'/g, "''");
}
