/**
 * Pure generators for instruction artifacts:
 *  - `.github/copilot-instructions.md` (concise, stack-seeded)
 *  - scoped `.github/instructions/*.instructions.md` with correct `applyTo` globs
 *  - a size guardrail so instructions stay lean by design.
 *
 * No `vscode` import — fully unit-testable.
 */
import { GeneratedFile } from '../apply/types';
import { StackAnalysis } from '../analyzer/types';
import { GeneratorContext, LANGUAGE_GLOBS, TECH_CONVENTIONS, testCommandFor } from './types';

/** Soft cap: instructions longer than this trigger a "too large" warning. */
export const INSTRUCTION_MAX_CHARS = 4000;
export const INSTRUCTION_MAX_LINES = 80;

export const COPILOT_INSTRUCTIONS_PATH = '.github/copilot-instructions.md';
export const SCOPED_INSTRUCTIONS_DIR = '.github/instructions';

export function buildCopilotInstructions(ctx: GeneratorContext): GeneratedFile {
  const { stack, structure } = ctx;
  const lines: string[] = [];

  lines.push(`# Copilot instructions: ${ctx.repoName}`);
  lines.push('');
  lines.push(summaryLine(stack));
  lines.push('');

  lines.push('## Stack');
  for (const item of stackBullets(stack)) {
    lines.push(`- ${item}`);
  }
  lines.push('');

  lines.push('## Layout');
  if (stack.layout === 'monorepo' && stack.modules.length > 0) {
    lines.push('Monorepo. Key modules:');
    for (const mod of stack.modules.slice(0, 8)) {
      const tech = mod.tech.length ? ` — ${mod.tech.join(', ')}` : '';
      lines.push(`- \`${mod.path}\`${mod.name ? ` (${mod.name})` : ''}${tech}`);
    }
  } else {
    const dirs = structure.topLevelDirs.filter((d) => d.name !== '.').slice(0, 8);
    for (const dir of dirs) {
      lines.push(`- \`${dir.name}/\``);
    }
    if (dirs.length === 0) {
      lines.push('- (flat layout)');
    }
  }
  lines.push('');

  lines.push('## Conventions');
  if (ctx.tailoredInstructions && ctx.tailoredInstructions.trim()) {
    lines.push(ctx.tailoredInstructions.trim());
  } else {
    for (const item of conventionBullets(stack)) {
      lines.push(`- ${item}`);
    }
    lines.push('- Keep changes minimal and scoped; do not touch generated/dependency directories.');
  }
  lines.push('');

  const testCmd = testCommandFor(stack);
  lines.push('## Working efficiently');
  if (testCmd) {
    lines.push(`- Run tests with \`${testCmd}\`.`);
  }
  if (ctx.hasArchitectureDoc) {
    lines.push('- See `ARCHITECTURE.md` for a map of the codebase before broad searches.');
  }
  if (ctx.hasContributingDoc) {
    lines.push('- Follow `CONTRIBUTING.md` for workflow and style.');
  }
  lines.push('- Prefer reading the specific files involved over broad repo-wide searches.');
  lines.push('');
  lines.push('<!-- Generated by Token Optimizer. Trim anything that is not essential. -->');

  return { relativePath: COPILOT_INSTRUCTIONS_PATH, content: lines.join('\n') + '\n' };
}

export function buildScopedInstructions(ctx: GeneratorContext): GeneratedFile[] {
  if (ctx.stack.layout === 'monorepo' && ctx.stack.modules.length > 0) {
    return ctx.stack.modules.slice(0, 10).map((mod) => {
      const slug = sanitizeSlug(mod.name ?? mod.path);
      const body = [
        '---',
        `applyTo: "${mod.path}/**"`,
        '---',
        `# ${mod.name ?? mod.path}`,
        '',
        `Scope: \`${mod.path}\`${mod.tech.length ? ` (${mod.tech.join(', ')})` : ''}.`,
        '',
        '- Add module-specific conventions here.',
        '- Keep this file short; it loads whenever these files are in context.',
        '',
      ].join('\n');
      return { relativePath: `${SCOPED_INSTRUCTIONS_DIR}/${slug}.instructions.md`, content: body };
    });
  }

  // Polyglot single project: one scoped file per primary language.
  const langs = ctx.stack.primaryLanguages.filter((l) => LANGUAGE_GLOBS[l]).slice(0, 4);
  return langs.map((lang) => {
    const globs = LANGUAGE_GLOBS[lang].join(', ');
    const slug = sanitizeSlug(lang);
    const convention = conventionForLanguage(lang, ctx.stack);
    const body = [
      '---',
      `applyTo: "${globs}"`,
      '---',
      `# ${lang} conventions`,
      '',
      convention ? `- ${convention}` : `- Add ${lang}-specific conventions here.`,
      '- Keep this file short and specific to these files.',
      '',
    ].join('\n');
    return { relativePath: `${SCOPED_INSTRUCTIONS_DIR}/${slug}.instructions.md`, content: body };
  });
}

export interface SizeWarning {
  path: string;
  chars: number;
  lines: number;
  message: string;
}

/** Return a warning if a generated instructions file is larger than the soft cap. */
export function checkInstructionSize(file: GeneratedFile): SizeWarning | undefined {
  const chars = file.content.length;
  const lines = file.content.split('\n').length;
  if (chars <= INSTRUCTION_MAX_CHARS && lines <= INSTRUCTION_MAX_LINES) {
    return undefined;
  }
  return {
    path: file.relativePath,
    chars,
    lines,
    message:
      `${file.relativePath} is large (${lines} lines, ${chars} chars). ` +
      'Long instructions are loaded on every request — trim to the essentials.',
  };
}

// ── helpers ─────────────────────────────────────────────────────────────────

function summaryLine(stack: StackAnalysis): string {
  const langs = stack.primaryLanguages.slice(0, 3).join(', ') || 'mixed';
  const layout = stack.layout === 'monorepo' ? 'monorepo' : 'single project';
  return `A ${layout} primarily in ${langs}. Keep guidance concise; this file is loaded on every agent request.`;
}

function stackBullets(stack: StackAnalysis): string[] {
  const out: string[] = [];
  if (stack.primaryLanguages.length) {
    out.push(`Languages: ${stack.primaryLanguages.slice(0, 5).join(', ')}`);
  }
  const frameworks = stack.tech.filter((t) => t.category === 'framework').map((t) => t.name);
  if (frameworks.length) {
    out.push(`Frameworks: ${frameworks.join(', ')}`);
  }
  const build = stack.tech.filter((t) => t.category === 'build' || t.category === 'runtime').map((t) => t.name);
  if (build.length) {
    out.push(`Build/runtime: ${build.join(', ')}`);
  }
  if (out.length === 0) {
    out.push('Stack not auto-detected — fill this in.');
  }
  return out;
}

function conventionBullets(stack: StackAnalysis): string[] {
  const out: string[] = [];
  for (const tech of stack.tech) {
    const hint = TECH_CONVENTIONS[tech.id];
    if (hint && !out.includes(hint)) {
      out.push(hint);
    }
  }
  if (out.length === 0) {
    out.push('Document the core conventions for this codebase here.');
  }
  return out.slice(0, 6);
}

function conventionForLanguage(lang: string, stack: StackAnalysis): string | undefined {
  const idByLang: Record<string, string> = {
    TypeScript: 'typescript',
    Python: 'python',
    Go: 'go',
    Rust: 'rust',
    Java: 'java',
  };
  const id = idByLang[lang];
  if (!id) {
    return undefined;
  }
  const detected = stack.tech.some((t) => t.id === id);
  return detected ? TECH_CONVENTIONS[id] : undefined;
}

function sanitizeSlug(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'scope'
  );
}
